/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.kotlin-application-conventions")
    id("org.springframework.boot") version "3.3.0" 
    id("io.spring.dependency-management") version "1.1.5"
//    kotlin("jvm") version "2.0.0"
    kotlin("plugin.spring") version "2.0.0"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("org.apache.commons:commons-text")
    implementation("com.azure:azure-core-serializer-json-gson:1.3.1")
    implementation("org.json:json:20090211")
    implementation(project(":utilities"))
    testImplementation("org.springframework.boot:spring-boot-starter-test")
}


application {
    // Define the main class for the application.
    mainClass = "com.example.demo.DemoApplicationKt"
}
